[package]
name = "pcap_cli"
version = "0.1.0"
authors = ["vlad <vladzhukovtirko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.7.0"
nom = "5.0.1"
clap = "2.33.0"
chrono = "0.4.9"